<?php
$holiday = array(
	'2019-1-1' => 'Tahun Baru Masehi',
	'2019-2-5' => 'Tahun Baru Imlek',
	'2019-3-7' => 'Hari Suci Nyepi',
	'2019-4-3' => 'Isro\' Mi\'roj',
	'2019-4-17' => 'Pemilu',
	'2019-4-19' => 'Jumat Agung',
	'2019-5-1' => 'Hari Buruh',
	'2019-5-19' => 'Hari Raya Waisak',
	'2019-5-30' => 'Kenaikan Isa Almasih',
	'2019-6-1' => 'Hari Lahir Pancasila',
	'2019-6-3' => 'Cuti Bersama',
	'2019-6-4' => 'Cuti Bersama',
	'2019-6-5' => 'Idul Fitri Hari Ke-1',
	'2019-6-6' => 'Idul Fitri Hari Ke-2',
	'2019-6-7' => 'Cuti Bersama',
	'2019-8-11' => 'Idul Adha',
	'2019-8-17' => 'Hari Kemerdekaan Indonesia',
	'2019-9-1' => 'Tahun Baru Hijriyah',
	'2019-11-9' => 'Maulid Nabi Muhammad SAW',
	'2019-12-24' => 'Cuti Bersama',
	'2019-12-25' => 'Hari Natal',);
?>